main:
  - name: 主页
    url: tour
    weight: 20
  - name: 研究方向
    url: interests
    weight: 30
  - name: 组内成员
    url: people
    weight: 40
  - name: 组内新闻
    url: post
    weight: 50
  - name: 论文发表
    url: publication
    weight: 60
  - name: 科研项目
    url: project
    weight: 60
  - name: 联系我们
    url: contact
    weight: 70